### ISSUE TITLE
Create User Login Page

### ISSUE THREAD

**Issue by Praveen4008** [Praveen4008/2426#1]
1. Create branch **devops**
2. Create an **Index.html**
3. Update two text fields i.e **Username** & **Password**
4. Update with **login Button**
5. add **Image**
6. A check box with **Remember Me**
7. A **Cancel Button**
8. Link with **Forgot Password**

![Login Form](https://github.com/user-attachments/assets/e0e1c010-d026-4b63-8ada-e59e5b966c4b)

**Comment by Kanna3149** [comment]
@Praveen4008 Sure let me create the same update you soon.

**Comment by Praveen4008** [comment]
@Kanna3149 Good Job
